version: '3'
services:
  db:
    container_name: 'mariadb'
    image: mariadb/server:10.5
    restart: always
    # si quieres cambiar envs corre `docker volume rm dev_dev_conf`
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    networks:
      app_net:
        ipv4_address: '192.168.1.10'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
networks:
  app_net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
volumes:
  db_data:
  db_conf:
